/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Role;
import BLL.Status;
import BLL.Stock;
import DAL.PharmacyException;
import DAL.StatusRepository;
import DAL.StockRepository;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Laris
 */
public class MainForm extends javax.swing.JFrame {

    StockRepository sr = new StockRepository();
    StatusRepository statusR = new StatusRepository();
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

    }

    public MainForm(Role role) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        refreshStock();
        if (role.getRoleID() != 1) {
            addUserBtn.setVisible(false);
            addClassificationBtn.setVisible(false);
            addMedicineBtn.setVisible(false);
            supplierBtn.setVisible(false);
        }
        logOut();

    }

    public void logOut() {
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
                Object[] ob = {"Yes", "No"};
                int i = JOptionPane.showOptionDialog(MainForm.this, "Do you want to log out?",
                        "Log Out", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[0]);
                if (i == 0) {
                    new LoginForm().setVisible(true);
                    MainForm.this.setVisible(false);
                }
            }
        });
    }

    @Override
    public synchronized void addWindowListener(WindowListener l) {
        super.addWindowListener(l); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        posBtn1 = new javax.swing.JButton();
        salesBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        addMedicineBtn = new javax.swing.JButton();
        addCostumerBtn = new javax.swing.JButton();
        addToStockBtn = new javax.swing.JButton();
        addClassificationBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        addUserBtn = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(682, 83));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pharmacy Management System");

        logOutBtn.setBackground(new java.awt.Color(255, 0, 0));
        logOutBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 763, Short.MAX_VALUE)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setOpaque(true);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(LoginForm.getUsername());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        posBtn1.setBackground(new java.awt.Color(0, 0, 0));
        posBtn1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        posBtn1.setForeground(new java.awt.Color(255, 255, 255));
        posBtn1.setText("POS");
        posBtn1.setToolTipText("Poin Of Sale");
        posBtn1.setBorder(null);
        posBtn1.setFocusPainted(false);
        posBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posBtn1ActionPerformed(evt);
            }
        });

        salesBtn.setBackground(new java.awt.Color(0, 0, 0));
        salesBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        salesBtn.setForeground(new java.awt.Color(255, 255, 255));
        salesBtn.setText("Sales");
        salesBtn.setBorder(null);
        salesBtn.setDefaultCapable(false);
        salesBtn.setFocusPainted(false);
        salesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBtnActionPerformed(evt);
            }
        });

        orderBtn.setBackground(new java.awt.Color(0, 0, 0));
        orderBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setText("Order");
        orderBtn.setBorder(null);
        orderBtn.setDefaultCapable(false);
        orderBtn.setFocusPainted(false);
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        addMedicineBtn.setBackground(new java.awt.Color(0, 0, 0));
        addMedicineBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addMedicineBtn.setForeground(new java.awt.Color(255, 255, 255));
        addMedicineBtn.setText("Medicine");
        addMedicineBtn.setBorder(null);
        addMedicineBtn.setDefaultCapable(false);
        addMedicineBtn.setFocusPainted(false);
        addMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicineBtnActionPerformed(evt);
            }
        });

        addCostumerBtn.setBackground(new java.awt.Color(0, 0, 0));
        addCostumerBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addCostumerBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCostumerBtn.setText("Customers");
        addCostumerBtn.setBorder(null);
        addCostumerBtn.setDefaultCapable(false);
        addCostumerBtn.setFocusPainted(false);
        addCostumerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCostumerBtnActionPerformed(evt);
            }
        });

        addToStockBtn.setBackground(new java.awt.Color(0, 0, 0));
        addToStockBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addToStockBtn.setForeground(new java.awt.Color(255, 255, 255));
        addToStockBtn.setText("Stock");
        addToStockBtn.setBorder(null);
        addToStockBtn.setDefaultCapable(false);
        addToStockBtn.setFocusPainted(false);
        addToStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToStockBtnActionPerformed(evt);
            }
        });

        addClassificationBtn.setBackground(new java.awt.Color(0, 0, 0));
        addClassificationBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addClassificationBtn.setForeground(new java.awt.Color(255, 255, 255));
        addClassificationBtn.setText("Classifications");
        addClassificationBtn.setBorder(null);
        addClassificationBtn.setDefaultCapable(false);
        addClassificationBtn.setFocusPainted(false);
        addClassificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassificationBtnActionPerformed(evt);
            }
        });

        supplierBtn.setBackground(new java.awt.Color(0, 0, 0));
        supplierBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        supplierBtn.setForeground(new java.awt.Color(255, 255, 255));
        supplierBtn.setText("Suppliers");
        supplierBtn.setBorder(null);
        supplierBtn.setDefaultCapable(false);
        supplierBtn.setFocusPainted(false);
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });

        addUserBtn.setBackground(new java.awt.Color(0, 0, 0));
        addUserBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        addUserBtn.setText("Users");
        addUserBtn.setBorder(null);
        addUserBtn.setDefaultCapable(false);
        addUserBtn.setFocusPainted(false);
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addClassificationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addToStockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCostumerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addMedicineBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(posBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addComponent(salesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(posBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addCostumerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addToStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addMedicineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addClassificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1554, Short.MAX_VALUE)
                    .addComponent(mainPanel)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        if (!(UserForm.getExists() == true)) {
            UserForm uf = new UserForm();
            mainPanel.add(uf);
            uf.show();
        }
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void addToStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToStockBtnActionPerformed
        if(!StockForm.isExists()){
            StockForm cf = new StockForm();
            mainPanel.add(cf);
            cf.show();
        }
    }//GEN-LAST:event_addToStockBtnActionPerformed

    private void addCostumerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCostumerBtnActionPerformed
        if (!CustomerForm.isExists()) {
            CustomerForm cf = new CustomerForm();
            mainPanel.add(cf);
            cf.show();
        }
    }//GEN-LAST:event_addCostumerBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        Object[] ob = {"Yes", "No"};
        int i = JOptionPane.showOptionDialog(this, "Do you want to log out?",
                "Log Out", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[0]);
        if (i == 0) {
            new LoginForm().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void addClassificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassificationBtnActionPerformed
        if (!ClassificationForm.isExists()) {
            ClassificationForm cf = new ClassificationForm();
            mainPanel.add(cf);
            cf.show();
        }
    }//GEN-LAST:event_addClassificationBtnActionPerformed

    private void addMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicineBtnActionPerformed
        if (!MedicineForm.isExists()) {
            MedicineForm mf = new MedicineForm();
            mainPanel.add(mf);
            mf.show();
        }
    }//GEN-LAST:event_addMedicineBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        if (!SupplierForm.isExists()) {
            SupplierForm sf = new SupplierForm();
            mainPanel.add(sf);
            sf.show();
        }
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void posBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posBtn1ActionPerformed
        // TODO add your handling code here:
        if(!POSForm.isExists()){
            try {
                POSForm pf = new POSForm();
                mainPanel.add(pf);
                pf.show();
            } catch (PharmacyException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_posBtn1ActionPerformed

    private void salesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBtnActionPerformed
        if(!SalesForm.isExists()){
            SalesForm sf = new SalesForm();
            mainPanel.add(sf);
            sf.show();
        }
    }//GEN-LAST:event_salesBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        if(!OrderForm.isExists()){
            OrderForm of = new OrderForm();
            mainPanel.add(of);
            of.show();
        }
    }//GEN-LAST:event_orderBtnActionPerformed

    public void refreshStock(){
        try {
            List<Stock> list = sr.findAll();
            Iterator it = list.iterator();
            for(int i=0; i<list.size();i++){
                Stock listItem = (Stock)it.next();
                if(listItem.getExpiryDate().before(Date.valueOf(LocalDate.now()))){
                    listItem.setStatusID(statusR.findByID(2));
                    sr.edit(listItem);
                }
            }
        } catch (PharmacyException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassificationBtn;
    private javax.swing.JButton addCostumerBtn;
    private javax.swing.JButton addMedicineBtn;
    private javax.swing.JButton addToStockBtn;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLayeredPane mainPanel;
    private javax.swing.JButton orderBtn;
    private javax.swing.JButton posBtn1;
    private javax.swing.JButton salesBtn;
    private javax.swing.JButton supplierBtn;
    // End of variables declaration//GEN-END:variables

}
