/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Medicine;
import BLL.Orders;
import BLL.Supplier;
import DAL.MedicineRepository;
import DAL.OrderRepository;
import DAL.PharmacyException;
import DAL.SupplierRepository;
import com.microsoft.sqlserver.jdbc.StringUtils;
import gui.Model.MedicineComboBoxModel;
import gui.Model.OrderTableModel;
import gui.Model.SupplierComboBoxModel;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Laris
 */
public class OrderForm extends javax.swing.JInternalFrame {

    private static boolean exists = false;
    
    OrderRepository or = new OrderRepository();
    OrderTableModel otm = new OrderTableModel();

    SupplierRepository sr = new SupplierRepository();
    SupplierComboBoxModel scbm;

    MedicineRepository mr = new MedicineRepository();
    MedicineComboBoxModel mcbm;

    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
        loadTable();
        loadComboBoxes();
        exists = true;
    }

    public static boolean isExists() {
        return exists;
    }

    public static void setExists(boolean exists) {
        OrderForm.exists = exists;
    }

    public void loadTable() {
        try {
            List<Orders> list = or.findAll();
            otm.addList(list);
            table.setModel(otm);
            otm.fireTableDataChanged();
        } catch (PharmacyException pe) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, pe);
        }
    }

    public void tableSelectedIndexChange() {
        final ListSelectionModel rowSM = table.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (lse.getValueIsAdjusting()) {
                    return;
                }

                ListSelectionModel rowSM = (ListSelectionModel) lse.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Orders o = otm.getOrders(selectedIndex);
                    idTxt.setText(o.getOrderID() + "");
                    supplierComboBox.setSelectedItem(o.getSupplierID());
                    supplierComboBox.repaint();
                    medicineComboBox.setSelectedItem(o.getMedicineID());
                    medicineComboBox.repaint();
                    quantityTxt.setText(o.getQuantity() + "");
                }
            }
        });
    }

    public void loadComboBoxes() {
        try {
            List<Supplier> supplierList = sr.findAll();
            scbm = new SupplierComboBoxModel(supplierList);
            supplierComboBox.setModel(scbm);
            supplierComboBox.repaint();

            List<Medicine> medicineList = mr.findAll();
            mcbm = new MedicineComboBoxModel(medicineList);
            medicineComboBox.setModel(mcbm);
            medicineComboBox.repaint();

        } catch (PharmacyException pe) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, pe);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        idTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        supplierComboBox = new javax.swing.JComboBox();
        medicineComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setClosable(true);
        setTitle("Order");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        idTxt.setEditable(false);

        jLabel1.setText("Order ID");

        jLabel2.setText("Supplier");

        supplierComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        medicineComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Medicine");

        jLabel4.setText("Quantity");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteBtn)
                        .addGap(44, 44, 44)
                        .addComponent(cancelBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveBtn))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int row = table.getSelectedRow();
        if (!(supplierComboBox.getSelectedItem() == null || medicineComboBox.getSelectedItem() == null
                || !StringUtils.isInteger(quantityTxt.getText()))) {
            if (row == -1) {
                Orders o = new Orders();
                o.setSupplierID((Supplier) supplierComboBox.getSelectedItem());
                o.setMedicineID((Medicine) medicineComboBox.getSelectedItem());
                o.setQuantity(Integer.parseInt(quantityTxt.getText()));
                o.setOrderDate(Date.valueOf(LocalDate.now()));
                o.setPrice(((Medicine) medicineComboBox.getSelectedItem()).getPrice() * Integer.parseInt(quantityTxt.getText()));
                try {
                    or.create(o);
                } catch (PharmacyException ex) {
                    JOptionPane.showMessageDialog(this, "MSG: " + ex.getMessage());
                }
            } else {
                Orders o = otm.getOrders(row);
                o.setSupplierID((Supplier) supplierComboBox.getSelectedItem());
                o.setMedicineID((Medicine) medicineComboBox.getSelectedItem());
                o.setQuantity(Integer.parseInt(quantityTxt.getText()));
                o.setOrderDate(Date.valueOf(LocalDate.now()));
                o.setPrice(((Medicine) medicineComboBox.getSelectedItem()).getPrice() * Integer.parseInt(quantityTxt.getText()));
                try{
                    or.edit(o);
                }catch(PharmacyException ex){
                    JOptionPane.showMessageDialog(this, "MSG: " + ex.getMessage());
                }
            }
            loadTable();
            clear();
        }else{
            JOptionPane.showMessageDialog(this, "Invalid input. Please check!");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        clear();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        exists = false;
    }//GEN-LAST:event_formInternalFrameClosed

    public void clear(){
        idTxt.setText("");
        supplierComboBox.setSelectedIndex(-1);
        medicineComboBox.setSelectedIndex(-1);
        quantityTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox medicineComboBox;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox supplierComboBox;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
